### ISSUE TITLE
Documentation for using action-versions on self-hosted runners

### ISSUE THREAD

**Issue by alec-drw** [actions/action-versions#10]
Hello! This project helps address many issues I have seen regarding rate limiting on self-hosted runners when checking out certain actions on GHES, even when using the "local" actions organization that has the default actions. However, there is no documentation on how to make use of this project - can the README or some documentation provide a high level "how to" set this up on runners built and maintained externally from the hosted runners?

**Comment by TingluoHuang** [comment]
Depends on where the rate limiting coming from, this cache might not work for you.
Based on my understanding, there are 2 potential API calls.
- Ask service to resolve an action to its SHA and verify policy around using the action (most likely get rate limited)
- Download the tar.gz/zip for the action (improved by this repo)

I think it might be better to figure out which case you are seeing before adopting the cache in this repository.

**Comment by alec-drw** [comment]
@TingluoHuang it seems some jobs get secondary rate limited, for example we have a workflow that spawns ~500 jobs and makes at least 468 API calls to our GHES and we have a secondary rate limit at 500 rps

```
Error: API rate limit exceeded while resolving action `actions/checkout@v4`.. API rate limit exceeded while resolving action `actions/download-artifact@v3`.. API rate limit exceeded while resolving action `actions/upload-artifact@v3`.. API rate limit exceeded while resolving action `aws-actions/configure-aws-credentials@v4`.
```

So putting the official actions on the runner may get us around this

**Comment by alec-drw** [comment]
Found the commit that adds support for this in runners (https://github.com/actions/runner/commit/f57ecd8e3c618e1723cdf02565e5f4da188776a4). My approach is to create a PV, mount it at `/opt/hostedactioncache` and populate that directory with the actions using the scripts here, and set `ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE` to that location. 

Going to give this a try Monday, if this sounds way off please let me know! Happy to write something for the ARC repo or similar based on the outcome.

**Comment by TingluoHuang** [comment]
@alec-drw you are getting `API rate limit exceeded while resolving action`, the cache will help you skip the actual tarball download, but it won't skip the `resolving action` part, which means you will still have chance to hit rate limiting. 😢
